name: Discord Notification
on:
  push:
    branches:
      - main  # Replace "main" with the branch you want to trigger the notification on

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK_ID: ${{ secrets.DISCORD_WEBHOOK_ID }}
          DISCORD_WEBHOOK_TOKEN: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "content": "New commit! Check out the latest changes: 'https://github.com/your-username/your-repo/commits/${{ github.ref }}'"
            }' \
            "https://discord.com/api/webhooks/${DISCORD_WEBHOOK_ID}/${DISCORD_WEBHOOK_TOKEN}"

